# Generated by Django 4.2.1 on 2023-05-16 11:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата создания комментария')),
            ],
            options={
                'verbose_name': 'Комментарий к обращению',
                'verbose_name_plural': 'Комментарии к обращениям',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Название компании',
                'verbose_name_plural': 'Названия компаний',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='Электронная почта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vova_crm.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=10, region='RU', unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номер телефоны',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(unique=True, verbose_name='Источник заявки')),
            ],
            options={
                'verbose_name': 'Источник заявок',
                'verbose_name_plural': 'Источники заявок',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Статус обращения')),
            ],
            options={
                'verbose_name': 'Статус обращения',
                'verbose_name_plural': 'Статусы обращений',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_receipt', models.DateField(verbose_name='Дата создания обращения')),
                ('last_contact_date', models.DateField(verbose_name='Дата последнего контакта с клиентом')),
                ('date_scheduled_call', models.DateField(verbose_name='Дата запланированного звонка')),
                ('conversion_goal', models.TextField(verbose_name='Цель обращения')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vova_crm.comment', verbose_name='Комментарии')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vova_crm.customer', verbose_name='Клиент')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vova_crm.source', verbose_name='Источник обращения')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vova_crm.status', verbose_name='Статус обращения')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vova_crm.phonenumber', verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vova_crm.region'),
        ),
    ]
