# Generated by Django 4.2.1 on 2023-05-29 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vova_crm', '0016_email_phonenumber_alter_customer_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.ManyToManyField(blank=True, to='vova_crm.email', verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.ManyToManyField(blank=True, to='vova_crm.phonenumber', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_receipt',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 14, 0, 3, 954818), verbose_name='Дата создания обращения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_contact_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 14, 0, 3, 954829), verbose_name='Дата последнего контакта с клиентом'),
        ),
    ]
