version: "3"
services:
  database:
    hostname: database
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5435" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - 5435:5432
    volumes:
      - elof_database2:/var/lib/postgresql/crm/data2
    networks:
      nw:
        aliases:
          - database
  crm:
      build: crm/
      command: /srv/telegram_admin/run.sh
      environment:
        - DATABASE_URL=database
        - DATABASE_PASSWORD=postgres
        - DATABASE_USER=postgres
        - DATABASE_PORT=5432
        - TABLE_NAME=ytb
        - DEBUG=False
        - SERVER=True
      ports:
        - 89:88
      depends_on:
        - database
      networks:
        nw:
          aliases:
            - crm

networks:
  nw:
  share:
    driver:
      bridge

volumes:
  elof_database2:
