version: "3"
services:
  database:
    hostname: database
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - elof_database:/var/lib/postgresql/data
    networks:
      nw:
        aliases:
          - database
  crm:
      build: crm/
      command: /srv/telegram_admin/run.sh
      ports:
        - 88:88
      depends_on:
        - database
      restart: always
      networks:
        nw:
          aliases:
            - crm

networks:
  nw:
  share:
    driver:
      bridge

volumes:
  elof_database:
