# Generated by Django 4.2.1 on 2023-05-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimedia', '0003_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.ManyToManyField(to='dimedia.comment', verbose_name='Комментарии'),
        ),
    ]
