# Generated by Django 4.2.1 on 2023-05-17 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimedia', '0006_alter_order_date_of_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_receipt',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 15, 26, 47, 97352), verbose_name='Дата создания обращения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_scheduled_call',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 15, 26, 47, 97367), verbose_name='Дата запланированного звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_contact_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 15, 26, 47, 97363), verbose_name='Дата последнего контакта с клиентом'),
        ),
    ]
