# Generated by Django 4.2.1 on 2023-05-17 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimedia', '0007_alter_order_date_of_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_receipt',
            field=models.DateField(default=datetime.datetime(2023, 5, 24, 15, 28, 7, 400881), verbose_name='Дата создания обращения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_scheduled_call',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 15, 28, 7, 400903), verbose_name='Дата запланированного звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_contact_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 15, 28, 7, 400895), verbose_name='Дата последнего контакта с клиентом'),
        ),
    ]
