# Generated by Django 4.2.1 on 2023-05-17 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dimedia', '0009_alter_order_date_of_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region='RU', unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimedia.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_receipt',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 15, 41, 31, 314414), verbose_name='Дата создания обращения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_scheduled_call',
            field=models.DateField(default=datetime.datetime(2023, 5, 24, 15, 41, 31, 314429), verbose_name='Дата запланированного звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_contact_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 15, 41, 31, 314425), verbose_name='Дата последнего контакта с клиентом'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
