# Generated by Django 4.2.1 on 2023-05-17 15:45

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dimedia', '0010_alter_customer_phone_number_alter_customer_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region='RU', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_receipt',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 15, 45, 18, 994938), verbose_name='Дата создания обращения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_scheduled_call',
            field=models.DateField(default=datetime.datetime(2023, 5, 24, 15, 45, 18, 994952), verbose_name='Дата запланированного звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_contact_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 15, 45, 18, 994948), verbose_name='Дата последнего контакта с клиентом'),
        ),
    ]
