# Generated by Django 4.2.1 on 2023-05-17 17:26

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dimedia', '0012_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '4. Название компании', 'verbose_name_plural': '4. Названия компаний'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '3. Клиент', 'verbose_name_plural': '3. Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '1. Обращение', 'verbose_name_plural': '1. Обращения'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '2. Регион', 'verbose_name_plural': '2. Регионы'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_receipt',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 17, 26, 27, 221737), verbose_name='Дата создания обращения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_scheduled_call',
            field=models.DateField(blank=True, null=True, verbose_name='Дата запланированного звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_contact_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 17, 26, 27, 221748), verbose_name='Дата последнего контакта с клиентом'),
        ),
    ]
