# Generated by Django 4.2.1 on 2023-05-17 17:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dimedia', '0013_alter_company_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_receipt',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 17, 49, 9, 288620), verbose_name='Дата создания обращения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_contact_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 17, 49, 9, 288631), verbose_name='Дата последнего контакта с клиентом'),
        ),
    ]
