# Generated by Django 4.2.1 on 2023-05-26 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dimedia', '0015_status_color_alter_order_date_of_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, unique=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Электронная почта',
                'verbose_name_plural': 'Электронные почты',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dimedia.company', verbose_name='Компания'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dimedia.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_receipt',
            field=models.DateField(default=datetime.datetime(2023, 5, 26, 14, 32, 45, 413394), verbose_name='Дата создания обращения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_contact_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 26, 14, 32, 45, 413404), verbose_name='Дата последнего контакта с клиентом'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.ManyToManyField(to='dimedia.email', verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.ManyToManyField(to='dimedia.phonenumber', verbose_name='Номер телефона'),
        ),
    ]
