# Generated by Django 4.2.1 on 2023-06-05 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimedia', '0018_alter_order_date_of_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_person',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_receipt',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 15, 28, 17, 231366), verbose_name='Дата создания обращения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_contact_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 15, 28, 17, 231376), verbose_name='Дата последнего контакта с клиентом'),
        ),
    ]
